<?php
namespace modava\calendar\components;

use backend\components\MyController;

class MyCalendarController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
